### ISSUE TITLE
incorrect vertical alignement of glyphs 

### ISSUE THREAD

**Issue by nxfs** [AustinJ235/basalt#20]
I've noted that the vertical glyphs seem not correctly aligned, this is especially visible in small fonts sizes.
Running from the vanilla example with increased scale:

![image](https://user-images.githubusercontent.com/6491972/126451892-c2d430cb-debd-48b5-a005-fa28329d2ef3.png)

**Comment by AustinJ235** [comment]
The code around text scaling isn't exactly ideal. Ilmenite currently has no concept of scale, so right now `Bin` calls for text of text_height * scale and then does some math (possibly incorrect) to fit it back down to 100% scale.

**Comment by AustinJ235** [comment]
Change the math around this will be resolved when ilmenite is upgraded.
