### ISSUE TITLE
your trangle example is broken

### ISSUE THREAD

**Issue by thinkrapido** [AustinJ235/basalt#25]
# Template

*   Version or commit of basalt: e525f98
*   OS (with kernel version for linux): 
* Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute

*   GPU: nvidia 1070
*   GPU Driver & Version: latest

# Issue

Please describe the issue and provide anything at all that will help resolve it.

cargo run --bin triangle
is not working. Other examples do

First errors

error[E0308]: mismatched types
  --> src/bin/triangle.rs:62:5
   |
62 |                 basalt.device(),
   |                 ^^^^^^^^^^^^^^^ expected struct `vulkano::device::Device`, found struct `basalt::vulkano::device::Device`
   |
   = note: expected struct `Arc<vulkano::device::Device>`
              found struct `Arc<basalt::vulkano::device::Device>`
   = note: perhaps two different versions of crate `vulkano` are being used?

error[E0308]: mismatched types
   --> src/bin/triangle.rs:111:48
    |
111 |             let triangle_vs = triangle_vs::Shader::load(basalt.device()).unwrap();
    |                                                         ^^^^^^^^^^^^^^^ expected struct `vulkano::device::Device`, found struct `basalt::vulkano::device::Device`
    |
    = note: expected struct `Arc<vulkano::device::Device>`
               found struct `Arc<basalt::vulkano::device::Device>`
    = note: perhaps two different versions of crate `vulkano` are being used?

error[E0308]: mismatched types
   --> src/bin/triangle.rs:112:48
    |
112 |             let triangle_fs = triangle_fs::Shader::load(basalt.device()).unwrap();
    |                                                         ^^^^^^^^^^^^^^^ expected struct `vulkano::device::Device`, found struct `basalt::vulkano::device::Device`
    |
    = note: expected struct `Arc<vulkano::device::Device>`
               found struct `Arc<basalt::vulkano::device::Device>`
    = note: perhaps two different versions of crate `vulkano` are being used?
...

**Comment by AustinJ235** [comment]
Fixed in https://github.com/AustinJ235/basalt/commit/ef057163fd3421dd4bcf1224dd25d3c7535ef599. Thanks for the report.
